# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /C/msys64/mingw64/bin/cmake.exe

# The command to remove a file.
RM = /C/msys64/mingw64/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /C/upload/open62541

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /C/upload/performaceTest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/C/msys64/mingw64/bin/cmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/C/msys64/mingw64/bin/cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/C/msys64/mingw64/bin/cpack.exe --config ./CPackSourceConfig.cmake C:/upload/performaceTest/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/C/msys64/mingw64/bin/cpack.exe --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/C/msys64/mingw64/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/C/msys64/mingw64/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /C/upload/performaceTest/CMakeFiles /C/upload/performaceTest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /C/upload/performaceTest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named open62541-generator-namespace

# Build rule for target.
open62541-generator-namespace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-namespace
.PHONY : open62541-generator-namespace

# fast build rule for target.
open62541-generator-namespace/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-namespace.dir/build.make CMakeFiles/open62541-generator-namespace.dir/build
.PHONY : open62541-generator-namespace/fast

#=============================================================================
# Target rules for targets named open62541-generator-statuscode

# Build rule for target.
open62541-generator-statuscode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-statuscode
.PHONY : open62541-generator-statuscode

# fast build rule for target.
open62541-generator-statuscode/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-statuscode.dir/build.make CMakeFiles/open62541-generator-statuscode.dir/build
.PHONY : open62541-generator-statuscode/fast

#=============================================================================
# Target rules for targets named open62541-generator-types

# Build rule for target.
open62541-generator-types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-types
.PHONY : open62541-generator-types

# fast build rule for target.
open62541-generator-types/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-types.dir/build.make CMakeFiles/open62541-generator-types.dir/build
.PHONY : open62541-generator-types/fast

#=============================================================================
# Target rules for targets named open62541-generator-ids-ns0

# Build rule for target.
open62541-generator-ids-ns0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-ids-ns0
.PHONY : open62541-generator-ids-ns0

# fast build rule for target.
open62541-generator-ids-ns0/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-ids-ns0.dir/build.make CMakeFiles/open62541-generator-ids-ns0.dir/build
.PHONY : open62541-generator-ids-ns0/fast

#=============================================================================
# Target rules for targets named open62541-generator-transport

# Build rule for target.
open62541-generator-transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-transport
.PHONY : open62541-generator-transport

# fast build rule for target.
open62541-generator-transport/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-transport.dir/build.make CMakeFiles/open62541-generator-transport.dir/build
.PHONY : open62541-generator-transport/fast

#=============================================================================
# Target rules for targets named cpplint

# Build rule for target.
cpplint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpplint
.PHONY : cpplint

# fast build rule for target.
cpplint/fast:
	$(MAKE) -f CMakeFiles/cpplint.dir/build.make CMakeFiles/cpplint.dir/build
.PHONY : cpplint/fast

#=============================================================================
# Target rules for targets named open62541-object

# Build rule for target.
open62541-object: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-object
.PHONY : open62541-object

# fast build rule for target.
open62541-object/fast:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/build
.PHONY : open62541-object/fast

#=============================================================================
# Target rules for targets named open62541-code-generation

# Build rule for target.
open62541-code-generation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-code-generation
.PHONY : open62541-code-generation

# fast build rule for target.
open62541-code-generation/fast:
	$(MAKE) -f CMakeFiles/open62541-code-generation.dir/build.make CMakeFiles/open62541-code-generation.dir/build
.PHONY : open62541-code-generation/fast

#=============================================================================
# Target rules for targets named open62541-plugins

# Build rule for target.
open62541-plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-plugins
.PHONY : open62541-plugins

# fast build rule for target.
open62541-plugins/fast:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/build
.PHONY : open62541-plugins/fast

#=============================================================================
# Target rules for targets named open62541

# Build rule for target.
open62541: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541
.PHONY : open62541

# fast build rule for target.
open62541/fast:
	$(MAKE) -f CMakeFiles/open62541.dir/build.make CMakeFiles/open62541.dir/build
.PHONY : open62541/fast

#=============================================================================
# Target rules for targets named clang-tidy

# Build rule for target.
clang-tidy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clang-tidy
.PHONY : clang-tidy

# fast build rule for target.
clang-tidy/fast:
	$(MAKE) -f CMakeFiles/clang-tidy.dir/build.make CMakeFiles/clang-tidy.dir/build
.PHONY : clang-tidy/fast

#=============================================================================
# Target rules for targets named doc_latex

# Build rule for target.
doc_latex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_latex
.PHONY : doc_latex

# fast build rule for target.
doc_latex/fast:
	$(MAKE) -f doc/CMakeFiles/doc_latex.dir/build.make doc/CMakeFiles/doc_latex.dir/build
.PHONY : doc_latex/fast

#=============================================================================
# Target rules for targets named doc_pdf

# Build rule for target.
doc_pdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_pdf
.PHONY : doc_pdf

# fast build rule for target.
doc_pdf/fast:
	$(MAKE) -f doc/CMakeFiles/doc_pdf.dir/build.make doc/CMakeFiles/doc_pdf.dir/build
.PHONY : doc_pdf/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f doc/CMakeFiles/doc.dir/build.make doc/CMakeFiles/doc.dir/build
.PHONY : doc/fast

arch/network_tcp.obj: arch/network_tcp.c.obj

.PHONY : arch/network_tcp.obj

# target to build an object file
arch/network_tcp.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/network_tcp.c.obj
.PHONY : arch/network_tcp.c.obj

arch/network_tcp.i: arch/network_tcp.c.i

.PHONY : arch/network_tcp.i

# target to preprocess a source file
arch/network_tcp.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/network_tcp.c.i
.PHONY : arch/network_tcp.c.i

arch/network_tcp.s: arch/network_tcp.c.s

.PHONY : arch/network_tcp.s

# target to generate assembly for a file
arch/network_tcp.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/network_tcp.c.s
.PHONY : arch/network_tcp.c.s

arch/win32/ua_architecture_functions.obj: arch/win32/ua_architecture_functions.c.obj

.PHONY : arch/win32/ua_architecture_functions.obj

# target to build an object file
arch/win32/ua_architecture_functions.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/win32/ua_architecture_functions.c.obj
.PHONY : arch/win32/ua_architecture_functions.c.obj

arch/win32/ua_architecture_functions.i: arch/win32/ua_architecture_functions.c.i

.PHONY : arch/win32/ua_architecture_functions.i

# target to preprocess a source file
arch/win32/ua_architecture_functions.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/win32/ua_architecture_functions.c.i
.PHONY : arch/win32/ua_architecture_functions.c.i

arch/win32/ua_architecture_functions.s: arch/win32/ua_architecture_functions.c.s

.PHONY : arch/win32/ua_architecture_functions.s

# target to generate assembly for a file
arch/win32/ua_architecture_functions.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/win32/ua_architecture_functions.c.s
.PHONY : arch/win32/ua_architecture_functions.c.s

arch/win32/ua_clock.obj: arch/win32/ua_clock.c.obj

.PHONY : arch/win32/ua_clock.obj

# target to build an object file
arch/win32/ua_clock.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/win32/ua_clock.c.obj
.PHONY : arch/win32/ua_clock.c.obj

arch/win32/ua_clock.i: arch/win32/ua_clock.c.i

.PHONY : arch/win32/ua_clock.i

# target to preprocess a source file
arch/win32/ua_clock.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/win32/ua_clock.c.i
.PHONY : arch/win32/ua_clock.c.i

arch/win32/ua_clock.s: arch/win32/ua_clock.c.s

.PHONY : arch/win32/ua_clock.s

# target to generate assembly for a file
arch/win32/ua_clock.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/arch/win32/ua_clock.c.s
.PHONY : arch/win32/ua_clock.c.s

deps/base64.obj: deps/base64.c.obj

.PHONY : deps/base64.obj

# target to build an object file
deps/base64.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/base64.c.obj
.PHONY : deps/base64.c.obj

deps/base64.i: deps/base64.c.i

.PHONY : deps/base64.i

# target to preprocess a source file
deps/base64.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/base64.c.i
.PHONY : deps/base64.c.i

deps/base64.s: deps/base64.c.s

.PHONY : deps/base64.s

# target to generate assembly for a file
deps/base64.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/base64.c.s
.PHONY : deps/base64.c.s

deps/libc_time.obj: deps/libc_time.c.obj

.PHONY : deps/libc_time.obj

# target to build an object file
deps/libc_time.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/libc_time.c.obj
.PHONY : deps/libc_time.c.obj

deps/libc_time.i: deps/libc_time.c.i

.PHONY : deps/libc_time.i

# target to preprocess a source file
deps/libc_time.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/libc_time.c.i
.PHONY : deps/libc_time.c.i

deps/libc_time.s: deps/libc_time.c.s

.PHONY : deps/libc_time.s

# target to generate assembly for a file
deps/libc_time.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/libc_time.c.s
.PHONY : deps/libc_time.c.s

deps/pcg_basic.obj: deps/pcg_basic.c.obj

.PHONY : deps/pcg_basic.obj

# target to build an object file
deps/pcg_basic.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/pcg_basic.c.obj
.PHONY : deps/pcg_basic.c.obj

deps/pcg_basic.i: deps/pcg_basic.c.i

.PHONY : deps/pcg_basic.i

# target to preprocess a source file
deps/pcg_basic.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/pcg_basic.c.i
.PHONY : deps/pcg_basic.c.i

deps/pcg_basic.s: deps/pcg_basic.c.s

.PHONY : deps/pcg_basic.s

# target to generate assembly for a file
deps/pcg_basic.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/deps/pcg_basic.c.s
.PHONY : deps/pcg_basic.c.s

plugins/securityPolicies/securitypolicy_mbedtls_common.obj: plugins/securityPolicies/securitypolicy_mbedtls_common.c.obj

.PHONY : plugins/securityPolicies/securitypolicy_mbedtls_common.obj

# target to build an object file
plugins/securityPolicies/securitypolicy_mbedtls_common.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/securitypolicy_mbedtls_common.c.obj
.PHONY : plugins/securityPolicies/securitypolicy_mbedtls_common.c.obj

plugins/securityPolicies/securitypolicy_mbedtls_common.i: plugins/securityPolicies/securitypolicy_mbedtls_common.c.i

.PHONY : plugins/securityPolicies/securitypolicy_mbedtls_common.i

# target to preprocess a source file
plugins/securityPolicies/securitypolicy_mbedtls_common.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/securitypolicy_mbedtls_common.c.i
.PHONY : plugins/securityPolicies/securitypolicy_mbedtls_common.c.i

plugins/securityPolicies/securitypolicy_mbedtls_common.s: plugins/securityPolicies/securitypolicy_mbedtls_common.c.s

.PHONY : plugins/securityPolicies/securitypolicy_mbedtls_common.s

# target to generate assembly for a file
plugins/securityPolicies/securitypolicy_mbedtls_common.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/securitypolicy_mbedtls_common.c.s
.PHONY : plugins/securityPolicies/securitypolicy_mbedtls_common.c.s

plugins/securityPolicies/ua_securitypolicy_basic128rsa15.obj: plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.obj

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic128rsa15.obj

# target to build an object file
plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.obj
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.obj

plugins/securityPolicies/ua_securitypolicy_basic128rsa15.i: plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.i

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic128rsa15.i

# target to preprocess a source file
plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.i
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.i

plugins/securityPolicies/ua_securitypolicy_basic128rsa15.s: plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.s

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic128rsa15.s

# target to generate assembly for a file
plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.s
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c.s

plugins/securityPolicies/ua_securitypolicy_basic256.obj: plugins/securityPolicies/ua_securitypolicy_basic256.c.obj

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256.obj

# target to build an object file
plugins/securityPolicies/ua_securitypolicy_basic256.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic256.c.obj
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256.c.obj

plugins/securityPolicies/ua_securitypolicy_basic256.i: plugins/securityPolicies/ua_securitypolicy_basic256.c.i

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256.i

# target to preprocess a source file
plugins/securityPolicies/ua_securitypolicy_basic256.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic256.c.i
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256.c.i

plugins/securityPolicies/ua_securitypolicy_basic256.s: plugins/securityPolicies/ua_securitypolicy_basic256.c.s

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256.s

# target to generate assembly for a file
plugins/securityPolicies/ua_securitypolicy_basic256.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic256.c.s
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256.c.s

plugins/securityPolicies/ua_securitypolicy_basic256sha256.obj: plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.obj

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256sha256.obj

# target to build an object file
plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.obj
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.obj

plugins/securityPolicies/ua_securitypolicy_basic256sha256.i: plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.i

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256sha256.i

# target to preprocess a source file
plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.i
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.i

plugins/securityPolicies/ua_securitypolicy_basic256sha256.s: plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.s

.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256sha256.s

# target to generate assembly for a file
plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.s
.PHONY : plugins/securityPolicies/ua_securitypolicy_basic256sha256.c.s

plugins/securityPolicies/ua_securitypolicy_none.obj: plugins/securityPolicies/ua_securitypolicy_none.c.obj

.PHONY : plugins/securityPolicies/ua_securitypolicy_none.obj

# target to build an object file
plugins/securityPolicies/ua_securitypolicy_none.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_none.c.obj
.PHONY : plugins/securityPolicies/ua_securitypolicy_none.c.obj

plugins/securityPolicies/ua_securitypolicy_none.i: plugins/securityPolicies/ua_securitypolicy_none.c.i

.PHONY : plugins/securityPolicies/ua_securitypolicy_none.i

# target to preprocess a source file
plugins/securityPolicies/ua_securitypolicy_none.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_none.c.i
.PHONY : plugins/securityPolicies/ua_securitypolicy_none.c.i

plugins/securityPolicies/ua_securitypolicy_none.s: plugins/securityPolicies/ua_securitypolicy_none.c.s

.PHONY : plugins/securityPolicies/ua_securitypolicy_none.s

# target to generate assembly for a file
plugins/securityPolicies/ua_securitypolicy_none.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/securityPolicies/ua_securitypolicy_none.c.s
.PHONY : plugins/securityPolicies/ua_securitypolicy_none.c.s

plugins/ua_accesscontrol_default.obj: plugins/ua_accesscontrol_default.c.obj

.PHONY : plugins/ua_accesscontrol_default.obj

# target to build an object file
plugins/ua_accesscontrol_default.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_accesscontrol_default.c.obj
.PHONY : plugins/ua_accesscontrol_default.c.obj

plugins/ua_accesscontrol_default.i: plugins/ua_accesscontrol_default.c.i

.PHONY : plugins/ua_accesscontrol_default.i

# target to preprocess a source file
plugins/ua_accesscontrol_default.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_accesscontrol_default.c.i
.PHONY : plugins/ua_accesscontrol_default.c.i

plugins/ua_accesscontrol_default.s: plugins/ua_accesscontrol_default.c.s

.PHONY : plugins/ua_accesscontrol_default.s

# target to generate assembly for a file
plugins/ua_accesscontrol_default.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_accesscontrol_default.c.s
.PHONY : plugins/ua_accesscontrol_default.c.s

plugins/ua_config_default.obj: plugins/ua_config_default.c.obj

.PHONY : plugins/ua_config_default.obj

# target to build an object file
plugins/ua_config_default.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_config_default.c.obj
.PHONY : plugins/ua_config_default.c.obj

plugins/ua_config_default.i: plugins/ua_config_default.c.i

.PHONY : plugins/ua_config_default.i

# target to preprocess a source file
plugins/ua_config_default.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_config_default.c.i
.PHONY : plugins/ua_config_default.c.i

plugins/ua_config_default.s: plugins/ua_config_default.c.s

.PHONY : plugins/ua_config_default.s

# target to generate assembly for a file
plugins/ua_config_default.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_config_default.c.s
.PHONY : plugins/ua_config_default.c.s

plugins/ua_log_stdout.obj: plugins/ua_log_stdout.c.obj

.PHONY : plugins/ua_log_stdout.obj

# target to build an object file
plugins/ua_log_stdout.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_log_stdout.c.obj
.PHONY : plugins/ua_log_stdout.c.obj

plugins/ua_log_stdout.i: plugins/ua_log_stdout.c.i

.PHONY : plugins/ua_log_stdout.i

# target to preprocess a source file
plugins/ua_log_stdout.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_log_stdout.c.i
.PHONY : plugins/ua_log_stdout.c.i

plugins/ua_log_stdout.s: plugins/ua_log_stdout.c.s

.PHONY : plugins/ua_log_stdout.s

# target to generate assembly for a file
plugins/ua_log_stdout.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_log_stdout.c.s
.PHONY : plugins/ua_log_stdout.c.s

plugins/ua_nodestore_hashmap.obj: plugins/ua_nodestore_hashmap.c.obj

.PHONY : plugins/ua_nodestore_hashmap.obj

# target to build an object file
plugins/ua_nodestore_hashmap.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_nodestore_hashmap.c.obj
.PHONY : plugins/ua_nodestore_hashmap.c.obj

plugins/ua_nodestore_hashmap.i: plugins/ua_nodestore_hashmap.c.i

.PHONY : plugins/ua_nodestore_hashmap.i

# target to preprocess a source file
plugins/ua_nodestore_hashmap.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_nodestore_hashmap.c.i
.PHONY : plugins/ua_nodestore_hashmap.c.i

plugins/ua_nodestore_hashmap.s: plugins/ua_nodestore_hashmap.c.s

.PHONY : plugins/ua_nodestore_hashmap.s

# target to generate assembly for a file
plugins/ua_nodestore_hashmap.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_nodestore_hashmap.c.s
.PHONY : plugins/ua_nodestore_hashmap.c.s

plugins/ua_nodestore_ziptree.obj: plugins/ua_nodestore_ziptree.c.obj

.PHONY : plugins/ua_nodestore_ziptree.obj

# target to build an object file
plugins/ua_nodestore_ziptree.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_nodestore_ziptree.c.obj
.PHONY : plugins/ua_nodestore_ziptree.c.obj

plugins/ua_nodestore_ziptree.i: plugins/ua_nodestore_ziptree.c.i

.PHONY : plugins/ua_nodestore_ziptree.i

# target to preprocess a source file
plugins/ua_nodestore_ziptree.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_nodestore_ziptree.c.i
.PHONY : plugins/ua_nodestore_ziptree.c.i

plugins/ua_nodestore_ziptree.s: plugins/ua_nodestore_ziptree.c.s

.PHONY : plugins/ua_nodestore_ziptree.s

# target to generate assembly for a file
plugins/ua_nodestore_ziptree.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_nodestore_ziptree.c.s
.PHONY : plugins/ua_nodestore_ziptree.c.s

plugins/ua_pki_default.obj: plugins/ua_pki_default.c.obj

.PHONY : plugins/ua_pki_default.obj

# target to build an object file
plugins/ua_pki_default.c.obj:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_pki_default.c.obj
.PHONY : plugins/ua_pki_default.c.obj

plugins/ua_pki_default.i: plugins/ua_pki_default.c.i

.PHONY : plugins/ua_pki_default.i

# target to preprocess a source file
plugins/ua_pki_default.c.i:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_pki_default.c.i
.PHONY : plugins/ua_pki_default.c.i

plugins/ua_pki_default.s: plugins/ua_pki_default.c.s

.PHONY : plugins/ua_pki_default.s

# target to generate assembly for a file
plugins/ua_pki_default.c.s:
	$(MAKE) -f CMakeFiles/open62541-plugins.dir/build.make CMakeFiles/open62541-plugins.dir/plugins/ua_pki_default.c.s
.PHONY : plugins/ua_pki_default.c.s

src/client/ua_client.obj: src/client/ua_client.c.obj

.PHONY : src/client/ua_client.obj

# target to build an object file
src/client/ua_client.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client.c.obj
.PHONY : src/client/ua_client.c.obj

src/client/ua_client.i: src/client/ua_client.c.i

.PHONY : src/client/ua_client.i

# target to preprocess a source file
src/client/ua_client.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client.c.i
.PHONY : src/client/ua_client.c.i

src/client/ua_client.s: src/client/ua_client.c.s

.PHONY : src/client/ua_client.s

# target to generate assembly for a file
src/client/ua_client.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client.c.s
.PHONY : src/client/ua_client.c.s

src/client/ua_client_connect.obj: src/client/ua_client_connect.c.obj

.PHONY : src/client/ua_client_connect.obj

# target to build an object file
src/client/ua_client_connect.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_connect.c.obj
.PHONY : src/client/ua_client_connect.c.obj

src/client/ua_client_connect.i: src/client/ua_client_connect.c.i

.PHONY : src/client/ua_client_connect.i

# target to preprocess a source file
src/client/ua_client_connect.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_connect.c.i
.PHONY : src/client/ua_client_connect.c.i

src/client/ua_client_connect.s: src/client/ua_client_connect.c.s

.PHONY : src/client/ua_client_connect.s

# target to generate assembly for a file
src/client/ua_client_connect.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_connect.c.s
.PHONY : src/client/ua_client_connect.c.s

src/client/ua_client_connect_async.obj: src/client/ua_client_connect_async.c.obj

.PHONY : src/client/ua_client_connect_async.obj

# target to build an object file
src/client/ua_client_connect_async.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_connect_async.c.obj
.PHONY : src/client/ua_client_connect_async.c.obj

src/client/ua_client_connect_async.i: src/client/ua_client_connect_async.c.i

.PHONY : src/client/ua_client_connect_async.i

# target to preprocess a source file
src/client/ua_client_connect_async.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_connect_async.c.i
.PHONY : src/client/ua_client_connect_async.c.i

src/client/ua_client_connect_async.s: src/client/ua_client_connect_async.c.s

.PHONY : src/client/ua_client_connect_async.s

# target to generate assembly for a file
src/client/ua_client_connect_async.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_connect_async.c.s
.PHONY : src/client/ua_client_connect_async.c.s

src/client/ua_client_discovery.obj: src/client/ua_client_discovery.c.obj

.PHONY : src/client/ua_client_discovery.obj

# target to build an object file
src/client/ua_client_discovery.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_discovery.c.obj
.PHONY : src/client/ua_client_discovery.c.obj

src/client/ua_client_discovery.i: src/client/ua_client_discovery.c.i

.PHONY : src/client/ua_client_discovery.i

# target to preprocess a source file
src/client/ua_client_discovery.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_discovery.c.i
.PHONY : src/client/ua_client_discovery.c.i

src/client/ua_client_discovery.s: src/client/ua_client_discovery.c.s

.PHONY : src/client/ua_client_discovery.s

# target to generate assembly for a file
src/client/ua_client_discovery.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_discovery.c.s
.PHONY : src/client/ua_client_discovery.c.s

src/client/ua_client_highlevel.obj: src/client/ua_client_highlevel.c.obj

.PHONY : src/client/ua_client_highlevel.obj

# target to build an object file
src/client/ua_client_highlevel.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_highlevel.c.obj
.PHONY : src/client/ua_client_highlevel.c.obj

src/client/ua_client_highlevel.i: src/client/ua_client_highlevel.c.i

.PHONY : src/client/ua_client_highlevel.i

# target to preprocess a source file
src/client/ua_client_highlevel.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_highlevel.c.i
.PHONY : src/client/ua_client_highlevel.c.i

src/client/ua_client_highlevel.s: src/client/ua_client_highlevel.c.s

.PHONY : src/client/ua_client_highlevel.s

# target to generate assembly for a file
src/client/ua_client_highlevel.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_highlevel.c.s
.PHONY : src/client/ua_client_highlevel.c.s

src/client/ua_client_subscriptions.obj: src/client/ua_client_subscriptions.c.obj

.PHONY : src/client/ua_client_subscriptions.obj

# target to build an object file
src/client/ua_client_subscriptions.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_subscriptions.c.obj
.PHONY : src/client/ua_client_subscriptions.c.obj

src/client/ua_client_subscriptions.i: src/client/ua_client_subscriptions.c.i

.PHONY : src/client/ua_client_subscriptions.i

# target to preprocess a source file
src/client/ua_client_subscriptions.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_subscriptions.c.i
.PHONY : src/client/ua_client_subscriptions.c.i

src/client/ua_client_subscriptions.s: src/client/ua_client_subscriptions.c.s

.PHONY : src/client/ua_client_subscriptions.s

# target to generate assembly for a file
src/client/ua_client_subscriptions.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_subscriptions.c.s
.PHONY : src/client/ua_client_subscriptions.c.s

src/client/ua_client_worker.obj: src/client/ua_client_worker.c.obj

.PHONY : src/client/ua_client_worker.obj

# target to build an object file
src/client/ua_client_worker.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_worker.c.obj
.PHONY : src/client/ua_client_worker.c.obj

src/client/ua_client_worker.i: src/client/ua_client_worker.c.i

.PHONY : src/client/ua_client_worker.i

# target to preprocess a source file
src/client/ua_client_worker.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_worker.c.i
.PHONY : src/client/ua_client_worker.c.i

src/client/ua_client_worker.s: src/client/ua_client_worker.c.s

.PHONY : src/client/ua_client_worker.s

# target to generate assembly for a file
src/client/ua_client_worker.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/client/ua_client_worker.c.s
.PHONY : src/client/ua_client_worker.c.s

src/pubsub/ua_pubsub_manager.obj: src/pubsub/ua_pubsub_manager.c.obj

.PHONY : src/pubsub/ua_pubsub_manager.obj

# target to build an object file
src/pubsub/ua_pubsub_manager.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_manager.c.obj
.PHONY : src/pubsub/ua_pubsub_manager.c.obj

src/pubsub/ua_pubsub_manager.i: src/pubsub/ua_pubsub_manager.c.i

.PHONY : src/pubsub/ua_pubsub_manager.i

# target to preprocess a source file
src/pubsub/ua_pubsub_manager.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_manager.c.i
.PHONY : src/pubsub/ua_pubsub_manager.c.i

src/pubsub/ua_pubsub_manager.s: src/pubsub/ua_pubsub_manager.c.s

.PHONY : src/pubsub/ua_pubsub_manager.s

# target to generate assembly for a file
src/pubsub/ua_pubsub_manager.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_manager.c.s
.PHONY : src/pubsub/ua_pubsub_manager.c.s

src/pubsub/ua_pubsub_networkmessage.obj: src/pubsub/ua_pubsub_networkmessage.c.obj

.PHONY : src/pubsub/ua_pubsub_networkmessage.obj

# target to build an object file
src/pubsub/ua_pubsub_networkmessage.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_networkmessage.c.obj
.PHONY : src/pubsub/ua_pubsub_networkmessage.c.obj

src/pubsub/ua_pubsub_networkmessage.i: src/pubsub/ua_pubsub_networkmessage.c.i

.PHONY : src/pubsub/ua_pubsub_networkmessage.i

# target to preprocess a source file
src/pubsub/ua_pubsub_networkmessage.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_networkmessage.c.i
.PHONY : src/pubsub/ua_pubsub_networkmessage.c.i

src/pubsub/ua_pubsub_networkmessage.s: src/pubsub/ua_pubsub_networkmessage.c.s

.PHONY : src/pubsub/ua_pubsub_networkmessage.s

# target to generate assembly for a file
src/pubsub/ua_pubsub_networkmessage.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_networkmessage.c.s
.PHONY : src/pubsub/ua_pubsub_networkmessage.c.s

src/pubsub/ua_pubsub_ns0.obj: src/pubsub/ua_pubsub_ns0.c.obj

.PHONY : src/pubsub/ua_pubsub_ns0.obj

# target to build an object file
src/pubsub/ua_pubsub_ns0.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_ns0.c.obj
.PHONY : src/pubsub/ua_pubsub_ns0.c.obj

src/pubsub/ua_pubsub_ns0.i: src/pubsub/ua_pubsub_ns0.c.i

.PHONY : src/pubsub/ua_pubsub_ns0.i

# target to preprocess a source file
src/pubsub/ua_pubsub_ns0.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_ns0.c.i
.PHONY : src/pubsub/ua_pubsub_ns0.c.i

src/pubsub/ua_pubsub_ns0.s: src/pubsub/ua_pubsub_ns0.c.s

.PHONY : src/pubsub/ua_pubsub_ns0.s

# target to generate assembly for a file
src/pubsub/ua_pubsub_ns0.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_ns0.c.s
.PHONY : src/pubsub/ua_pubsub_ns0.c.s

src/pubsub/ua_pubsub_reader.obj: src/pubsub/ua_pubsub_reader.c.obj

.PHONY : src/pubsub/ua_pubsub_reader.obj

# target to build an object file
src/pubsub/ua_pubsub_reader.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_reader.c.obj
.PHONY : src/pubsub/ua_pubsub_reader.c.obj

src/pubsub/ua_pubsub_reader.i: src/pubsub/ua_pubsub_reader.c.i

.PHONY : src/pubsub/ua_pubsub_reader.i

# target to preprocess a source file
src/pubsub/ua_pubsub_reader.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_reader.c.i
.PHONY : src/pubsub/ua_pubsub_reader.c.i

src/pubsub/ua_pubsub_reader.s: src/pubsub/ua_pubsub_reader.c.s

.PHONY : src/pubsub/ua_pubsub_reader.s

# target to generate assembly for a file
src/pubsub/ua_pubsub_reader.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_reader.c.s
.PHONY : src/pubsub/ua_pubsub_reader.c.s

src/pubsub/ua_pubsub_writer.obj: src/pubsub/ua_pubsub_writer.c.obj

.PHONY : src/pubsub/ua_pubsub_writer.obj

# target to build an object file
src/pubsub/ua_pubsub_writer.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_writer.c.obj
.PHONY : src/pubsub/ua_pubsub_writer.c.obj

src/pubsub/ua_pubsub_writer.i: src/pubsub/ua_pubsub_writer.c.i

.PHONY : src/pubsub/ua_pubsub_writer.i

# target to preprocess a source file
src/pubsub/ua_pubsub_writer.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_writer.c.i
.PHONY : src/pubsub/ua_pubsub_writer.c.i

src/pubsub/ua_pubsub_writer.s: src/pubsub/ua_pubsub_writer.c.s

.PHONY : src/pubsub/ua_pubsub_writer.s

# target to generate assembly for a file
src/pubsub/ua_pubsub_writer.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/pubsub/ua_pubsub_writer.c.s
.PHONY : src/pubsub/ua_pubsub_writer.c.s

src/server/ua_discovery_manager.obj: src/server/ua_discovery_manager.c.obj

.PHONY : src/server/ua_discovery_manager.obj

# target to build an object file
src/server/ua_discovery_manager.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_discovery_manager.c.obj
.PHONY : src/server/ua_discovery_manager.c.obj

src/server/ua_discovery_manager.i: src/server/ua_discovery_manager.c.i

.PHONY : src/server/ua_discovery_manager.i

# target to preprocess a source file
src/server/ua_discovery_manager.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_discovery_manager.c.i
.PHONY : src/server/ua_discovery_manager.c.i

src/server/ua_discovery_manager.s: src/server/ua_discovery_manager.c.s

.PHONY : src/server/ua_discovery_manager.s

# target to generate assembly for a file
src/server/ua_discovery_manager.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_discovery_manager.c.s
.PHONY : src/server/ua_discovery_manager.c.s

src/server/ua_nodes.obj: src/server/ua_nodes.c.obj

.PHONY : src/server/ua_nodes.obj

# target to build an object file
src/server/ua_nodes.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_nodes.c.obj
.PHONY : src/server/ua_nodes.c.obj

src/server/ua_nodes.i: src/server/ua_nodes.c.i

.PHONY : src/server/ua_nodes.i

# target to preprocess a source file
src/server/ua_nodes.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_nodes.c.i
.PHONY : src/server/ua_nodes.c.i

src/server/ua_nodes.s: src/server/ua_nodes.c.s

.PHONY : src/server/ua_nodes.s

# target to generate assembly for a file
src/server/ua_nodes.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_nodes.c.s
.PHONY : src/server/ua_nodes.c.s

src/server/ua_server.obj: src/server/ua_server.c.obj

.PHONY : src/server/ua_server.obj

# target to build an object file
src/server/ua_server.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server.c.obj
.PHONY : src/server/ua_server.c.obj

src/server/ua_server.i: src/server/ua_server.c.i

.PHONY : src/server/ua_server.i

# target to preprocess a source file
src/server/ua_server.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server.c.i
.PHONY : src/server/ua_server.c.i

src/server/ua_server.s: src/server/ua_server.c.s

.PHONY : src/server/ua_server.s

# target to generate assembly for a file
src/server/ua_server.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server.c.s
.PHONY : src/server/ua_server.c.s

src/server/ua_server_async.obj: src/server/ua_server_async.c.obj

.PHONY : src/server/ua_server_async.obj

# target to build an object file
src/server/ua_server_async.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_async.c.obj
.PHONY : src/server/ua_server_async.c.obj

src/server/ua_server_async.i: src/server/ua_server_async.c.i

.PHONY : src/server/ua_server_async.i

# target to preprocess a source file
src/server/ua_server_async.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_async.c.i
.PHONY : src/server/ua_server_async.c.i

src/server/ua_server_async.s: src/server/ua_server_async.c.s

.PHONY : src/server/ua_server_async.s

# target to generate assembly for a file
src/server/ua_server_async.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_async.c.s
.PHONY : src/server/ua_server_async.c.s

src/server/ua_server_binary.obj: src/server/ua_server_binary.c.obj

.PHONY : src/server/ua_server_binary.obj

# target to build an object file
src/server/ua_server_binary.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_binary.c.obj
.PHONY : src/server/ua_server_binary.c.obj

src/server/ua_server_binary.i: src/server/ua_server_binary.c.i

.PHONY : src/server/ua_server_binary.i

# target to preprocess a source file
src/server/ua_server_binary.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_binary.c.i
.PHONY : src/server/ua_server_binary.c.i

src/server/ua_server_binary.s: src/server/ua_server_binary.c.s

.PHONY : src/server/ua_server_binary.s

# target to generate assembly for a file
src/server/ua_server_binary.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_binary.c.s
.PHONY : src/server/ua_server_binary.c.s

src/server/ua_server_config.obj: src/server/ua_server_config.c.obj

.PHONY : src/server/ua_server_config.obj

# target to build an object file
src/server/ua_server_config.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_config.c.obj
.PHONY : src/server/ua_server_config.c.obj

src/server/ua_server_config.i: src/server/ua_server_config.c.i

.PHONY : src/server/ua_server_config.i

# target to preprocess a source file
src/server/ua_server_config.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_config.c.i
.PHONY : src/server/ua_server_config.c.i

src/server/ua_server_config.s: src/server/ua_server_config.c.s

.PHONY : src/server/ua_server_config.s

# target to generate assembly for a file
src/server/ua_server_config.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_config.c.s
.PHONY : src/server/ua_server_config.c.s

src/server/ua_server_discovery.obj: src/server/ua_server_discovery.c.obj

.PHONY : src/server/ua_server_discovery.obj

# target to build an object file
src/server/ua_server_discovery.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_discovery.c.obj
.PHONY : src/server/ua_server_discovery.c.obj

src/server/ua_server_discovery.i: src/server/ua_server_discovery.c.i

.PHONY : src/server/ua_server_discovery.i

# target to preprocess a source file
src/server/ua_server_discovery.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_discovery.c.i
.PHONY : src/server/ua_server_discovery.c.i

src/server/ua_server_discovery.s: src/server/ua_server_discovery.c.s

.PHONY : src/server/ua_server_discovery.s

# target to generate assembly for a file
src/server/ua_server_discovery.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_discovery.c.s
.PHONY : src/server/ua_server_discovery.c.s

src/server/ua_server_ns0.obj: src/server/ua_server_ns0.c.obj

.PHONY : src/server/ua_server_ns0.obj

# target to build an object file
src/server/ua_server_ns0.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_ns0.c.obj
.PHONY : src/server/ua_server_ns0.c.obj

src/server/ua_server_ns0.i: src/server/ua_server_ns0.c.i

.PHONY : src/server/ua_server_ns0.i

# target to preprocess a source file
src/server/ua_server_ns0.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_ns0.c.i
.PHONY : src/server/ua_server_ns0.c.i

src/server/ua_server_ns0.s: src/server/ua_server_ns0.c.s

.PHONY : src/server/ua_server_ns0.s

# target to generate assembly for a file
src/server/ua_server_ns0.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_ns0.c.s
.PHONY : src/server/ua_server_ns0.c.s

src/server/ua_server_utils.obj: src/server/ua_server_utils.c.obj

.PHONY : src/server/ua_server_utils.obj

# target to build an object file
src/server/ua_server_utils.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_utils.c.obj
.PHONY : src/server/ua_server_utils.c.obj

src/server/ua_server_utils.i: src/server/ua_server_utils.c.i

.PHONY : src/server/ua_server_utils.i

# target to preprocess a source file
src/server/ua_server_utils.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_utils.c.i
.PHONY : src/server/ua_server_utils.c.i

src/server/ua_server_utils.s: src/server/ua_server_utils.c.s

.PHONY : src/server/ua_server_utils.s

# target to generate assembly for a file
src/server/ua_server_utils.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_server_utils.c.s
.PHONY : src/server/ua_server_utils.c.s

src/server/ua_services_attribute.obj: src/server/ua_services_attribute.c.obj

.PHONY : src/server/ua_services_attribute.obj

# target to build an object file
src/server/ua_services_attribute.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_attribute.c.obj
.PHONY : src/server/ua_services_attribute.c.obj

src/server/ua_services_attribute.i: src/server/ua_services_attribute.c.i

.PHONY : src/server/ua_services_attribute.i

# target to preprocess a source file
src/server/ua_services_attribute.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_attribute.c.i
.PHONY : src/server/ua_services_attribute.c.i

src/server/ua_services_attribute.s: src/server/ua_services_attribute.c.s

.PHONY : src/server/ua_services_attribute.s

# target to generate assembly for a file
src/server/ua_services_attribute.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_attribute.c.s
.PHONY : src/server/ua_services_attribute.c.s

src/server/ua_services_discovery.obj: src/server/ua_services_discovery.c.obj

.PHONY : src/server/ua_services_discovery.obj

# target to build an object file
src/server/ua_services_discovery.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_discovery.c.obj
.PHONY : src/server/ua_services_discovery.c.obj

src/server/ua_services_discovery.i: src/server/ua_services_discovery.c.i

.PHONY : src/server/ua_services_discovery.i

# target to preprocess a source file
src/server/ua_services_discovery.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_discovery.c.i
.PHONY : src/server/ua_services_discovery.c.i

src/server/ua_services_discovery.s: src/server/ua_services_discovery.c.s

.PHONY : src/server/ua_services_discovery.s

# target to generate assembly for a file
src/server/ua_services_discovery.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_discovery.c.s
.PHONY : src/server/ua_services_discovery.c.s

src/server/ua_services_discovery_multicast.obj: src/server/ua_services_discovery_multicast.c.obj

.PHONY : src/server/ua_services_discovery_multicast.obj

# target to build an object file
src/server/ua_services_discovery_multicast.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_discovery_multicast.c.obj
.PHONY : src/server/ua_services_discovery_multicast.c.obj

src/server/ua_services_discovery_multicast.i: src/server/ua_services_discovery_multicast.c.i

.PHONY : src/server/ua_services_discovery_multicast.i

# target to preprocess a source file
src/server/ua_services_discovery_multicast.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_discovery_multicast.c.i
.PHONY : src/server/ua_services_discovery_multicast.c.i

src/server/ua_services_discovery_multicast.s: src/server/ua_services_discovery_multicast.c.s

.PHONY : src/server/ua_services_discovery_multicast.s

# target to generate assembly for a file
src/server/ua_services_discovery_multicast.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_discovery_multicast.c.s
.PHONY : src/server/ua_services_discovery_multicast.c.s

src/server/ua_services_method.obj: src/server/ua_services_method.c.obj

.PHONY : src/server/ua_services_method.obj

# target to build an object file
src/server/ua_services_method.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_method.c.obj
.PHONY : src/server/ua_services_method.c.obj

src/server/ua_services_method.i: src/server/ua_services_method.c.i

.PHONY : src/server/ua_services_method.i

# target to preprocess a source file
src/server/ua_services_method.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_method.c.i
.PHONY : src/server/ua_services_method.c.i

src/server/ua_services_method.s: src/server/ua_services_method.c.s

.PHONY : src/server/ua_services_method.s

# target to generate assembly for a file
src/server/ua_services_method.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_method.c.s
.PHONY : src/server/ua_services_method.c.s

src/server/ua_services_monitoreditem.obj: src/server/ua_services_monitoreditem.c.obj

.PHONY : src/server/ua_services_monitoreditem.obj

# target to build an object file
src/server/ua_services_monitoreditem.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_monitoreditem.c.obj
.PHONY : src/server/ua_services_monitoreditem.c.obj

src/server/ua_services_monitoreditem.i: src/server/ua_services_monitoreditem.c.i

.PHONY : src/server/ua_services_monitoreditem.i

# target to preprocess a source file
src/server/ua_services_monitoreditem.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_monitoreditem.c.i
.PHONY : src/server/ua_services_monitoreditem.c.i

src/server/ua_services_monitoreditem.s: src/server/ua_services_monitoreditem.c.s

.PHONY : src/server/ua_services_monitoreditem.s

# target to generate assembly for a file
src/server/ua_services_monitoreditem.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_monitoreditem.c.s
.PHONY : src/server/ua_services_monitoreditem.c.s

src/server/ua_services_nodemanagement.obj: src/server/ua_services_nodemanagement.c.obj

.PHONY : src/server/ua_services_nodemanagement.obj

# target to build an object file
src/server/ua_services_nodemanagement.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_nodemanagement.c.obj
.PHONY : src/server/ua_services_nodemanagement.c.obj

src/server/ua_services_nodemanagement.i: src/server/ua_services_nodemanagement.c.i

.PHONY : src/server/ua_services_nodemanagement.i

# target to preprocess a source file
src/server/ua_services_nodemanagement.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_nodemanagement.c.i
.PHONY : src/server/ua_services_nodemanagement.c.i

src/server/ua_services_nodemanagement.s: src/server/ua_services_nodemanagement.c.s

.PHONY : src/server/ua_services_nodemanagement.s

# target to generate assembly for a file
src/server/ua_services_nodemanagement.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_nodemanagement.c.s
.PHONY : src/server/ua_services_nodemanagement.c.s

src/server/ua_services_securechannel.obj: src/server/ua_services_securechannel.c.obj

.PHONY : src/server/ua_services_securechannel.obj

# target to build an object file
src/server/ua_services_securechannel.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_securechannel.c.obj
.PHONY : src/server/ua_services_securechannel.c.obj

src/server/ua_services_securechannel.i: src/server/ua_services_securechannel.c.i

.PHONY : src/server/ua_services_securechannel.i

# target to preprocess a source file
src/server/ua_services_securechannel.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_securechannel.c.i
.PHONY : src/server/ua_services_securechannel.c.i

src/server/ua_services_securechannel.s: src/server/ua_services_securechannel.c.s

.PHONY : src/server/ua_services_securechannel.s

# target to generate assembly for a file
src/server/ua_services_securechannel.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_securechannel.c.s
.PHONY : src/server/ua_services_securechannel.c.s

src/server/ua_services_session.obj: src/server/ua_services_session.c.obj

.PHONY : src/server/ua_services_session.obj

# target to build an object file
src/server/ua_services_session.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_session.c.obj
.PHONY : src/server/ua_services_session.c.obj

src/server/ua_services_session.i: src/server/ua_services_session.c.i

.PHONY : src/server/ua_services_session.i

# target to preprocess a source file
src/server/ua_services_session.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_session.c.i
.PHONY : src/server/ua_services_session.c.i

src/server/ua_services_session.s: src/server/ua_services_session.c.s

.PHONY : src/server/ua_services_session.s

# target to generate assembly for a file
src/server/ua_services_session.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_session.c.s
.PHONY : src/server/ua_services_session.c.s

src/server/ua_services_subscription.obj: src/server/ua_services_subscription.c.obj

.PHONY : src/server/ua_services_subscription.obj

# target to build an object file
src/server/ua_services_subscription.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_subscription.c.obj
.PHONY : src/server/ua_services_subscription.c.obj

src/server/ua_services_subscription.i: src/server/ua_services_subscription.c.i

.PHONY : src/server/ua_services_subscription.i

# target to preprocess a source file
src/server/ua_services_subscription.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_subscription.c.i
.PHONY : src/server/ua_services_subscription.c.i

src/server/ua_services_subscription.s: src/server/ua_services_subscription.c.s

.PHONY : src/server/ua_services_subscription.s

# target to generate assembly for a file
src/server/ua_services_subscription.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_subscription.c.s
.PHONY : src/server/ua_services_subscription.c.s

src/server/ua_services_view.obj: src/server/ua_services_view.c.obj

.PHONY : src/server/ua_services_view.obj

# target to build an object file
src/server/ua_services_view.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_view.c.obj
.PHONY : src/server/ua_services_view.c.obj

src/server/ua_services_view.i: src/server/ua_services_view.c.i

.PHONY : src/server/ua_services_view.i

# target to preprocess a source file
src/server/ua_services_view.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_view.c.i
.PHONY : src/server/ua_services_view.c.i

src/server/ua_services_view.s: src/server/ua_services_view.c.s

.PHONY : src/server/ua_services_view.s

# target to generate assembly for a file
src/server/ua_services_view.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_services_view.c.s
.PHONY : src/server/ua_services_view.c.s

src/server/ua_session.obj: src/server/ua_session.c.obj

.PHONY : src/server/ua_session.obj

# target to build an object file
src/server/ua_session.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_session.c.obj
.PHONY : src/server/ua_session.c.obj

src/server/ua_session.i: src/server/ua_session.c.i

.PHONY : src/server/ua_session.i

# target to preprocess a source file
src/server/ua_session.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_session.c.i
.PHONY : src/server/ua_session.c.i

src/server/ua_session.s: src/server/ua_session.c.s

.PHONY : src/server/ua_session.s

# target to generate assembly for a file
src/server/ua_session.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_session.c.s
.PHONY : src/server/ua_session.c.s

src/server/ua_subscription.obj: src/server/ua_subscription.c.obj

.PHONY : src/server/ua_subscription.obj

# target to build an object file
src/server/ua_subscription.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription.c.obj
.PHONY : src/server/ua_subscription.c.obj

src/server/ua_subscription.i: src/server/ua_subscription.c.i

.PHONY : src/server/ua_subscription.i

# target to preprocess a source file
src/server/ua_subscription.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription.c.i
.PHONY : src/server/ua_subscription.c.i

src/server/ua_subscription.s: src/server/ua_subscription.c.s

.PHONY : src/server/ua_subscription.s

# target to generate assembly for a file
src/server/ua_subscription.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription.c.s
.PHONY : src/server/ua_subscription.c.s

src/server/ua_subscription_datachange.obj: src/server/ua_subscription_datachange.c.obj

.PHONY : src/server/ua_subscription_datachange.obj

# target to build an object file
src/server/ua_subscription_datachange.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription_datachange.c.obj
.PHONY : src/server/ua_subscription_datachange.c.obj

src/server/ua_subscription_datachange.i: src/server/ua_subscription_datachange.c.i

.PHONY : src/server/ua_subscription_datachange.i

# target to preprocess a source file
src/server/ua_subscription_datachange.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription_datachange.c.i
.PHONY : src/server/ua_subscription_datachange.c.i

src/server/ua_subscription_datachange.s: src/server/ua_subscription_datachange.c.s

.PHONY : src/server/ua_subscription_datachange.s

# target to generate assembly for a file
src/server/ua_subscription_datachange.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription_datachange.c.s
.PHONY : src/server/ua_subscription_datachange.c.s

src/server/ua_subscription_monitoreditem.obj: src/server/ua_subscription_monitoreditem.c.obj

.PHONY : src/server/ua_subscription_monitoreditem.obj

# target to build an object file
src/server/ua_subscription_monitoreditem.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription_monitoreditem.c.obj
.PHONY : src/server/ua_subscription_monitoreditem.c.obj

src/server/ua_subscription_monitoreditem.i: src/server/ua_subscription_monitoreditem.c.i

.PHONY : src/server/ua_subscription_monitoreditem.i

# target to preprocess a source file
src/server/ua_subscription_monitoreditem.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription_monitoreditem.c.i
.PHONY : src/server/ua_subscription_monitoreditem.c.i

src/server/ua_subscription_monitoreditem.s: src/server/ua_subscription_monitoreditem.c.s

.PHONY : src/server/ua_subscription_monitoreditem.s

# target to generate assembly for a file
src/server/ua_subscription_monitoreditem.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/server/ua_subscription_monitoreditem.c.s
.PHONY : src/server/ua_subscription_monitoreditem.c.s

src/ua_connection.obj: src/ua_connection.c.obj

.PHONY : src/ua_connection.obj

# target to build an object file
src/ua_connection.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_connection.c.obj
.PHONY : src/ua_connection.c.obj

src/ua_connection.i: src/ua_connection.c.i

.PHONY : src/ua_connection.i

# target to preprocess a source file
src/ua_connection.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_connection.c.i
.PHONY : src/ua_connection.c.i

src/ua_connection.s: src/ua_connection.c.s

.PHONY : src/ua_connection.s

# target to generate assembly for a file
src/ua_connection.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_connection.c.s
.PHONY : src/ua_connection.c.s

src/ua_securechannel.obj: src/ua_securechannel.c.obj

.PHONY : src/ua_securechannel.obj

# target to build an object file
src/ua_securechannel.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_securechannel.c.obj
.PHONY : src/ua_securechannel.c.obj

src/ua_securechannel.i: src/ua_securechannel.c.i

.PHONY : src/ua_securechannel.i

# target to preprocess a source file
src/ua_securechannel.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_securechannel.c.i
.PHONY : src/ua_securechannel.c.i

src/ua_securechannel.s: src/ua_securechannel.c.s

.PHONY : src/ua_securechannel.s

# target to generate assembly for a file
src/ua_securechannel.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_securechannel.c.s
.PHONY : src/ua_securechannel.c.s

src/ua_securechannel_crypto.obj: src/ua_securechannel_crypto.c.obj

.PHONY : src/ua_securechannel_crypto.obj

# target to build an object file
src/ua_securechannel_crypto.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_securechannel_crypto.c.obj
.PHONY : src/ua_securechannel_crypto.c.obj

src/ua_securechannel_crypto.i: src/ua_securechannel_crypto.c.i

.PHONY : src/ua_securechannel_crypto.i

# target to preprocess a source file
src/ua_securechannel_crypto.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_securechannel_crypto.c.i
.PHONY : src/ua_securechannel_crypto.c.i

src/ua_securechannel_crypto.s: src/ua_securechannel_crypto.c.s

.PHONY : src/ua_securechannel_crypto.s

# target to generate assembly for a file
src/ua_securechannel_crypto.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_securechannel_crypto.c.s
.PHONY : src/ua_securechannel_crypto.c.s

src/ua_timer.obj: src/ua_timer.c.obj

.PHONY : src/ua_timer.obj

# target to build an object file
src/ua_timer.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_timer.c.obj
.PHONY : src/ua_timer.c.obj

src/ua_timer.i: src/ua_timer.c.i

.PHONY : src/ua_timer.i

# target to preprocess a source file
src/ua_timer.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_timer.c.i
.PHONY : src/ua_timer.c.i

src/ua_timer.s: src/ua_timer.c.s

.PHONY : src/ua_timer.s

# target to generate assembly for a file
src/ua_timer.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_timer.c.s
.PHONY : src/ua_timer.c.s

src/ua_types.obj: src/ua_types.c.obj

.PHONY : src/ua_types.obj

# target to build an object file
src/ua_types.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_types.c.obj
.PHONY : src/ua_types.c.obj

src/ua_types.i: src/ua_types.c.i

.PHONY : src/ua_types.i

# target to preprocess a source file
src/ua_types.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_types.c.i
.PHONY : src/ua_types.c.i

src/ua_types.s: src/ua_types.c.s

.PHONY : src/ua_types.s

# target to generate assembly for a file
src/ua_types.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_types.c.s
.PHONY : src/ua_types.c.s

src/ua_types_encoding_binary.obj: src/ua_types_encoding_binary.c.obj

.PHONY : src/ua_types_encoding_binary.obj

# target to build an object file
src/ua_types_encoding_binary.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_types_encoding_binary.c.obj
.PHONY : src/ua_types_encoding_binary.c.obj

src/ua_types_encoding_binary.i: src/ua_types_encoding_binary.c.i

.PHONY : src/ua_types_encoding_binary.i

# target to preprocess a source file
src/ua_types_encoding_binary.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_types_encoding_binary.c.i
.PHONY : src/ua_types_encoding_binary.c.i

src/ua_types_encoding_binary.s: src/ua_types_encoding_binary.c.s

.PHONY : src/ua_types_encoding_binary.s

# target to generate assembly for a file
src/ua_types_encoding_binary.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_types_encoding_binary.c.s
.PHONY : src/ua_types_encoding_binary.c.s

src/ua_util.obj: src/ua_util.c.obj

.PHONY : src/ua_util.obj

# target to build an object file
src/ua_util.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_util.c.obj
.PHONY : src/ua_util.c.obj

src/ua_util.i: src/ua_util.c.i

.PHONY : src/ua_util.i

# target to preprocess a source file
src/ua_util.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_util.c.i
.PHONY : src/ua_util.c.i

src/ua_util.s: src/ua_util.c.s

.PHONY : src/ua_util.s

# target to generate assembly for a file
src/ua_util.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_util.c.s
.PHONY : src/ua_util.c.s

src/ua_workqueue.obj: src/ua_workqueue.c.obj

.PHONY : src/ua_workqueue.obj

# target to build an object file
src/ua_workqueue.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_workqueue.c.obj
.PHONY : src/ua_workqueue.c.obj

src/ua_workqueue.i: src/ua_workqueue.c.i

.PHONY : src/ua_workqueue.i

# target to preprocess a source file
src/ua_workqueue.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_workqueue.c.i
.PHONY : src/ua_workqueue.c.i

src/ua_workqueue.s: src/ua_workqueue.c.s

.PHONY : src/ua_workqueue.s

# target to generate assembly for a file
src/ua_workqueue.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src/ua_workqueue.c.s
.PHONY : src/ua_workqueue.c.s

src_generated/open62541/namespace0_generated.obj: src_generated/open62541/namespace0_generated.c.obj

.PHONY : src_generated/open62541/namespace0_generated.obj

# target to build an object file
src_generated/open62541/namespace0_generated.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/namespace0_generated.c.obj
.PHONY : src_generated/open62541/namespace0_generated.c.obj

src_generated/open62541/namespace0_generated.i: src_generated/open62541/namespace0_generated.c.i

.PHONY : src_generated/open62541/namespace0_generated.i

# target to preprocess a source file
src_generated/open62541/namespace0_generated.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/namespace0_generated.c.i
.PHONY : src_generated/open62541/namespace0_generated.c.i

src_generated/open62541/namespace0_generated.s: src_generated/open62541/namespace0_generated.c.s

.PHONY : src_generated/open62541/namespace0_generated.s

# target to generate assembly for a file
src_generated/open62541/namespace0_generated.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/namespace0_generated.c.s
.PHONY : src_generated/open62541/namespace0_generated.c.s

src_generated/open62541/statuscodes.obj: src_generated/open62541/statuscodes.c.obj

.PHONY : src_generated/open62541/statuscodes.obj

# target to build an object file
src_generated/open62541/statuscodes.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/statuscodes.c.obj
.PHONY : src_generated/open62541/statuscodes.c.obj

src_generated/open62541/statuscodes.i: src_generated/open62541/statuscodes.c.i

.PHONY : src_generated/open62541/statuscodes.i

# target to preprocess a source file
src_generated/open62541/statuscodes.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/statuscodes.c.i
.PHONY : src_generated/open62541/statuscodes.c.i

src_generated/open62541/statuscodes.s: src_generated/open62541/statuscodes.c.s

.PHONY : src_generated/open62541/statuscodes.s

# target to generate assembly for a file
src_generated/open62541/statuscodes.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/statuscodes.c.s
.PHONY : src_generated/open62541/statuscodes.c.s

src_generated/open62541/transport_generated.obj: src_generated/open62541/transport_generated.c.obj

.PHONY : src_generated/open62541/transport_generated.obj

# target to build an object file
src_generated/open62541/transport_generated.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/transport_generated.c.obj
.PHONY : src_generated/open62541/transport_generated.c.obj

src_generated/open62541/transport_generated.i: src_generated/open62541/transport_generated.c.i

.PHONY : src_generated/open62541/transport_generated.i

# target to preprocess a source file
src_generated/open62541/transport_generated.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/transport_generated.c.i
.PHONY : src_generated/open62541/transport_generated.c.i

src_generated/open62541/transport_generated.s: src_generated/open62541/transport_generated.c.s

.PHONY : src_generated/open62541/transport_generated.s

# target to generate assembly for a file
src_generated/open62541/transport_generated.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/transport_generated.c.s
.PHONY : src_generated/open62541/transport_generated.c.s

src_generated/open62541/types_generated.obj: src_generated/open62541/types_generated.c.obj

.PHONY : src_generated/open62541/types_generated.obj

# target to build an object file
src_generated/open62541/types_generated.c.obj:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/types_generated.c.obj
.PHONY : src_generated/open62541/types_generated.c.obj

src_generated/open62541/types_generated.i: src_generated/open62541/types_generated.c.i

.PHONY : src_generated/open62541/types_generated.i

# target to preprocess a source file
src_generated/open62541/types_generated.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/types_generated.c.i
.PHONY : src_generated/open62541/types_generated.c.i

src_generated/open62541/types_generated.s: src_generated/open62541/types_generated.c.s

.PHONY : src_generated/open62541/types_generated.s

# target to generate assembly for a file
src_generated/open62541/types_generated.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/src_generated/open62541/types_generated.c.s
.PHONY : src_generated/open62541/types_generated.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... install"
	@echo "... open62541-generator-namespace"
	@echo "... open62541-generator-statuscode"
	@echo "... open62541-generator-types"
	@echo "... open62541-generator-ids-ns0"
	@echo "... open62541-generator-transport"
	@echo "... cpplint"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... open62541-object"
	@echo "... open62541-code-generation"
	@echo "... open62541-plugins"
	@echo "... open62541"
	@echo "... install/local"
	@echo "... clang-tidy"
	@echo "... doc_latex"
	@echo "... doc_pdf"
	@echo "... doc"
	@echo "... arch/network_tcp.obj"
	@echo "... arch/network_tcp.i"
	@echo "... arch/network_tcp.s"
	@echo "... arch/win32/ua_architecture_functions.obj"
	@echo "... arch/win32/ua_architecture_functions.i"
	@echo "... arch/win32/ua_architecture_functions.s"
	@echo "... arch/win32/ua_clock.obj"
	@echo "... arch/win32/ua_clock.i"
	@echo "... arch/win32/ua_clock.s"
	@echo "... deps/base64.obj"
	@echo "... deps/base64.i"
	@echo "... deps/base64.s"
	@echo "... deps/libc_time.obj"
	@echo "... deps/libc_time.i"
	@echo "... deps/libc_time.s"
	@echo "... deps/pcg_basic.obj"
	@echo "... deps/pcg_basic.i"
	@echo "... deps/pcg_basic.s"
	@echo "... plugins/securityPolicies/securitypolicy_mbedtls_common.obj"
	@echo "... plugins/securityPolicies/securitypolicy_mbedtls_common.i"
	@echo "... plugins/securityPolicies/securitypolicy_mbedtls_common.s"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic128rsa15.obj"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic128rsa15.i"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic128rsa15.s"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic256.obj"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic256.i"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic256.s"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic256sha256.obj"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic256sha256.i"
	@echo "... plugins/securityPolicies/ua_securitypolicy_basic256sha256.s"
	@echo "... plugins/securityPolicies/ua_securitypolicy_none.obj"
	@echo "... plugins/securityPolicies/ua_securitypolicy_none.i"
	@echo "... plugins/securityPolicies/ua_securitypolicy_none.s"
	@echo "... plugins/ua_accesscontrol_default.obj"
	@echo "... plugins/ua_accesscontrol_default.i"
	@echo "... plugins/ua_accesscontrol_default.s"
	@echo "... plugins/ua_config_default.obj"
	@echo "... plugins/ua_config_default.i"
	@echo "... plugins/ua_config_default.s"
	@echo "... plugins/ua_log_stdout.obj"
	@echo "... plugins/ua_log_stdout.i"
	@echo "... plugins/ua_log_stdout.s"
	@echo "... plugins/ua_nodestore_hashmap.obj"
	@echo "... plugins/ua_nodestore_hashmap.i"
	@echo "... plugins/ua_nodestore_hashmap.s"
	@echo "... plugins/ua_nodestore_ziptree.obj"
	@echo "... plugins/ua_nodestore_ziptree.i"
	@echo "... plugins/ua_nodestore_ziptree.s"
	@echo "... plugins/ua_pki_default.obj"
	@echo "... plugins/ua_pki_default.i"
	@echo "... plugins/ua_pki_default.s"
	@echo "... src/client/ua_client.obj"
	@echo "... src/client/ua_client.i"
	@echo "... src/client/ua_client.s"
	@echo "... src/client/ua_client_connect.obj"
	@echo "... src/client/ua_client_connect.i"
	@echo "... src/client/ua_client_connect.s"
	@echo "... src/client/ua_client_connect_async.obj"
	@echo "... src/client/ua_client_connect_async.i"
	@echo "... src/client/ua_client_connect_async.s"
	@echo "... src/client/ua_client_discovery.obj"
	@echo "... src/client/ua_client_discovery.i"
	@echo "... src/client/ua_client_discovery.s"
	@echo "... src/client/ua_client_highlevel.obj"
	@echo "... src/client/ua_client_highlevel.i"
	@echo "... src/client/ua_client_highlevel.s"
	@echo "... src/client/ua_client_subscriptions.obj"
	@echo "... src/client/ua_client_subscriptions.i"
	@echo "... src/client/ua_client_subscriptions.s"
	@echo "... src/client/ua_client_worker.obj"
	@echo "... src/client/ua_client_worker.i"
	@echo "... src/client/ua_client_worker.s"
	@echo "... src/pubsub/ua_pubsub_manager.obj"
	@echo "... src/pubsub/ua_pubsub_manager.i"
	@echo "... src/pubsub/ua_pubsub_manager.s"
	@echo "... src/pubsub/ua_pubsub_networkmessage.obj"
	@echo "... src/pubsub/ua_pubsub_networkmessage.i"
	@echo "... src/pubsub/ua_pubsub_networkmessage.s"
	@echo "... src/pubsub/ua_pubsub_ns0.obj"
	@echo "... src/pubsub/ua_pubsub_ns0.i"
	@echo "... src/pubsub/ua_pubsub_ns0.s"
	@echo "... src/pubsub/ua_pubsub_reader.obj"
	@echo "... src/pubsub/ua_pubsub_reader.i"
	@echo "... src/pubsub/ua_pubsub_reader.s"
	@echo "... src/pubsub/ua_pubsub_writer.obj"
	@echo "... src/pubsub/ua_pubsub_writer.i"
	@echo "... src/pubsub/ua_pubsub_writer.s"
	@echo "... src/server/ua_discovery_manager.obj"
	@echo "... src/server/ua_discovery_manager.i"
	@echo "... src/server/ua_discovery_manager.s"
	@echo "... src/server/ua_nodes.obj"
	@echo "... src/server/ua_nodes.i"
	@echo "... src/server/ua_nodes.s"
	@echo "... src/server/ua_server.obj"
	@echo "... src/server/ua_server.i"
	@echo "... src/server/ua_server.s"
	@echo "... src/server/ua_server_async.obj"
	@echo "... src/server/ua_server_async.i"
	@echo "... src/server/ua_server_async.s"
	@echo "... src/server/ua_server_binary.obj"
	@echo "... src/server/ua_server_binary.i"
	@echo "... src/server/ua_server_binary.s"
	@echo "... src/server/ua_server_config.obj"
	@echo "... src/server/ua_server_config.i"
	@echo "... src/server/ua_server_config.s"
	@echo "... src/server/ua_server_discovery.obj"
	@echo "... src/server/ua_server_discovery.i"
	@echo "... src/server/ua_server_discovery.s"
	@echo "... src/server/ua_server_ns0.obj"
	@echo "... src/server/ua_server_ns0.i"
	@echo "... src/server/ua_server_ns0.s"
	@echo "... src/server/ua_server_utils.obj"
	@echo "... src/server/ua_server_utils.i"
	@echo "... src/server/ua_server_utils.s"
	@echo "... src/server/ua_services_attribute.obj"
	@echo "... src/server/ua_services_attribute.i"
	@echo "... src/server/ua_services_attribute.s"
	@echo "... src/server/ua_services_discovery.obj"
	@echo "... src/server/ua_services_discovery.i"
	@echo "... src/server/ua_services_discovery.s"
	@echo "... src/server/ua_services_discovery_multicast.obj"
	@echo "... src/server/ua_services_discovery_multicast.i"
	@echo "... src/server/ua_services_discovery_multicast.s"
	@echo "... src/server/ua_services_method.obj"
	@echo "... src/server/ua_services_method.i"
	@echo "... src/server/ua_services_method.s"
	@echo "... src/server/ua_services_monitoreditem.obj"
	@echo "... src/server/ua_services_monitoreditem.i"
	@echo "... src/server/ua_services_monitoreditem.s"
	@echo "... src/server/ua_services_nodemanagement.obj"
	@echo "... src/server/ua_services_nodemanagement.i"
	@echo "... src/server/ua_services_nodemanagement.s"
	@echo "... src/server/ua_services_securechannel.obj"
	@echo "... src/server/ua_services_securechannel.i"
	@echo "... src/server/ua_services_securechannel.s"
	@echo "... src/server/ua_services_session.obj"
	@echo "... src/server/ua_services_session.i"
	@echo "... src/server/ua_services_session.s"
	@echo "... src/server/ua_services_subscription.obj"
	@echo "... src/server/ua_services_subscription.i"
	@echo "... src/server/ua_services_subscription.s"
	@echo "... src/server/ua_services_view.obj"
	@echo "... src/server/ua_services_view.i"
	@echo "... src/server/ua_services_view.s"
	@echo "... src/server/ua_session.obj"
	@echo "... src/server/ua_session.i"
	@echo "... src/server/ua_session.s"
	@echo "... src/server/ua_subscription.obj"
	@echo "... src/server/ua_subscription.i"
	@echo "... src/server/ua_subscription.s"
	@echo "... src/server/ua_subscription_datachange.obj"
	@echo "... src/server/ua_subscription_datachange.i"
	@echo "... src/server/ua_subscription_datachange.s"
	@echo "... src/server/ua_subscription_monitoreditem.obj"
	@echo "... src/server/ua_subscription_monitoreditem.i"
	@echo "... src/server/ua_subscription_monitoreditem.s"
	@echo "... src/ua_connection.obj"
	@echo "... src/ua_connection.i"
	@echo "... src/ua_connection.s"
	@echo "... src/ua_securechannel.obj"
	@echo "... src/ua_securechannel.i"
	@echo "... src/ua_securechannel.s"
	@echo "... src/ua_securechannel_crypto.obj"
	@echo "... src/ua_securechannel_crypto.i"
	@echo "... src/ua_securechannel_crypto.s"
	@echo "... src/ua_timer.obj"
	@echo "... src/ua_timer.i"
	@echo "... src/ua_timer.s"
	@echo "... src/ua_types.obj"
	@echo "... src/ua_types.i"
	@echo "... src/ua_types.s"
	@echo "... src/ua_types_encoding_binary.obj"
	@echo "... src/ua_types_encoding_binary.i"
	@echo "... src/ua_types_encoding_binary.s"
	@echo "... src/ua_util.obj"
	@echo "... src/ua_util.i"
	@echo "... src/ua_util.s"
	@echo "... src/ua_workqueue.obj"
	@echo "... src/ua_workqueue.i"
	@echo "... src/ua_workqueue.s"
	@echo "... src_generated/open62541/namespace0_generated.obj"
	@echo "... src_generated/open62541/namespace0_generated.i"
	@echo "... src_generated/open62541/namespace0_generated.s"
	@echo "... src_generated/open62541/statuscodes.obj"
	@echo "... src_generated/open62541/statuscodes.i"
	@echo "... src_generated/open62541/statuscodes.s"
	@echo "... src_generated/open62541/transport_generated.obj"
	@echo "... src_generated/open62541/transport_generated.i"
	@echo "... src_generated/open62541/transport_generated.s"
	@echo "... src_generated/open62541/types_generated.obj"
	@echo "... src_generated/open62541/types_generated.i"
	@echo "... src_generated/open62541/types_generated.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

